# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Benedictuspoort Informatica Beheer
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
Informaticabeheer is een richting waarin je een uitgebrijde kennis krijgt over software en hardware.
Je leert in software programmeren in C#, html, CSS, JS, en gebruikt en leert over nog vele anderen.
In hardware leer je hoe een computer in elkaar zit, je zal leren hoe je voor een server van bijvoorbeeld een bedrijf kan zorgen.
Over het algemeen leer je een heel brede basis die later van pas zal komen, en waarmee je nog in elke richting uit kunt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.benedictuspoortInformaticaBeheer.be" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
